version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: Cinder1014
      MYSQL_DATABASE: employee_management
      MYSQL_USER: root
      MYSQL_PASSWORD: Cinder1014
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    image: kyoka74022/employee-management-backend:latest
    container_name: employee_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: EmployeeManagement
      SPRINGDOC_API_DOCS_PATH: /api-docs
      SERVER_SERVLET_CONTEXT_PATH: /api
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/employee_management?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Cinder1014
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL5InnoDBDialect
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: DEBUG
    depends_on:
      - mysql-db

volumes:
  mysql_data:
